#!/usr/bin/env bash
# Sync oam_flux sources into the self-contained Hugging Face Space folder.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/src/oam_flux"
DST="$ROOT/space/oam_flux"

mkdir -p "$DST/oam_flux"
rm -rf "$DST/oam_flux"/*.py

COMMIT="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo dev)"
UPDATED="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cat > "$DST/build_info.py" <<EOF
"""Auto-generated by scripts/sync_hf_space.sh — do not edit by hand."""

BUILD_COMMIT = "$COMMIT"
BUILD_UPDATED_UTC = "$UPDATED"
EOF

cp "$SRC"/*.py "$DST/oam_flux/"
# app.py and demo_core.py live in space/oam_flux/ (edited in place)

# HF installs gradio from README sdk_version — do not pin gradio here.
cat > "$DST/requirements.txt" <<'EOF'
numpy>=1.24.0,<3.0.0
scipy>=1.10.0
matplotlib>=3.7.0
pyyaml>=6.0
Pillow>=10.0.0
# Do not pin pydantic — gradio 6.19[mcp] requires pydantic>=2.11.10
audioop-lts>=0.2.1; python_version >= "3.13"
EOF

cp "$ROOT/configs/default.yaml" "$DST/configs_default.yaml"

{
  cat <<'EOF'
---
title: OAM–Flux
emoji: 🌀
colorFrom: purple
colorTo: blue
sdk: gradio
sdk_version: 6.19.0
python_version: '3.13'
app_file: app.py
pinned: false
license: mit
short_description: OAM photon flux on gauged Hopf lattice flywheels
---

EOF
  cat <<'BODY'

# OAM–Flux — Hugging Face Space

**Browser demo** of [oam_flux](https://github.com/kinaar8340/oam_flux): VQC helical OAM propagation coupled to gauged Hopf lattice flux flywheels, with mystery-style emergence probes (R, e⁻², golden-angle @ λt=2).

## Tabs

| Tab | Description |
|-----|-------------|
| **VQC Coupling** | Multi-ℓ propagation heatmap, flux kick slice, lattice timeseries |
| **Emergence** | κ/ℓ survival sweeps vs mystery analogs |
| **Analytic** | Fast v0.1 OAM packet baseline |

## Related

- [toe](https://github.com/kinaar8340/toe) — gauged Hopf lattice substrate
- [vqc_sims_public](https://github.com/kinaar8340/vqc_sims_public) — OAM photonics layer
- [mystery](https://github.com/kinaar8340/mystery) — φ/e/π emergence probes

BODY
} > "$DST/README.md"

echo "Synced → $DST (commit $COMMIT)"